# -*- coding: cp1252 -*-
#This file is automatically generated!  Modifications will be deleted!
filters = ['Blues', 'Cycles', 'Exotic', 'Jazz', 'Maqam', 'Mela', 'Modal', 'Modern', 'Pop', 'Raga', 'Rock', 'Tonal']