#!/usr/local/bin/python
""" Scaleslib.py
----------------------------
Author:    Luke Paireepinart
Copyright: Nico Schuler

Texas State University
Summer 2009
----------------------------
Brief Summary: This is just a definition of all of the different scales the Scales program supports.
The scales are just stored in a dictionary with a mapping from scale name to a tuple containing
a list of the note steps (integers) as the first item and a list of filter keywords for the second.
"""
scales =    {
            'Major Scale'                          : ([2, 2, 1, 2, 2, 2, 1],    ["Tonal","Jazz","Rock", "Pop"]),
            'Natural Minor Scale'                  : ([2, 1, 2, 2, 1, 2, 2],    ["Tonal"]),
            'Minor Pentatonic Scale'               : ([3, 2, 2, 3, 2],          ["Exotic"]),
            'Blues Scale'                          : ([3, 2, 1, 1, 3, 2],       ["Blues"]),
            'Harmonic Minor Scale'                 : ([2, 1, 2, 2, 1, 3, 1],    ["Tonal"]),
            'Half-Step-Minor-Third Scale'          : ([1, 3, 1, 3, 1, 3],       ["Modern"]),
            'Pentatonic Scale'                     : ([2, 2, 3, 2, 3],          ["Blues"]),
            'Octatonic-1 Scale'                    : ([1, 2, 1, 2, 1, 2, 1, 2], ["Modern"]),
            'Octatonic-2 Scale'                    : ([2, 1, 2, 1, 2, 1, 2, 1], ["Modern"]),
            'Algerian Scale'                       : ([2, 1, 2, 1, 1, 1, 3, 1], ["Exotic"]),
            'Harmonic Major Scale'                 : ([2, 2, 1, 2, 1, 3, 1],    ["Exotic"]),
            'Double Harmonic Major (Arabic) Scale' : ([1, 3, 1, 2, 1, 3, 1],    ["Exotic"]),
            'Double Harmonic Minor Scale'          : ([1, 3, 1, 1, 3, 1],       ["Exotic"]),
            'Hungarian Gypsy Scale'                : ([2, 1, 3, 1, 1, 3, 1],    ["Exotic"]),
            'Hungarian Minor Scale'                : ([2, 1, 3, 1, 1, 3, 1],    ["Exotic"]),
            'Hungarian Folk Scale'                 : ([1, 3, 1, 2, 1, 3, 1],    ["Exotic"]),
            'Phrygian Dominant (Jewish) Scale'     : ([1, 3, 1, 2, 1, 2, 2],    ["Exotic"]),
            'Egyptian Scale'                       : ([2, 1, 3, 1, 1, 3, 1],    ["Exotic"]),
            'Eskimo Tetratonic Scale'              : ([2, 2, 3, 5],             ["Exotic"]),
            'Eskimo Hexatonic Scale'               : ([2, 2, 2, 2, 1, 3],       ["Exotic"]),
            'Scottish Hexatonic Scale'             : ([2, 2, 1, 2, 2, 3],       ["Exotic"]),
            'Oriental Scale'                       : ([2, 3, 4, 1, 2],          ["Exotic"]),
            'Oriental Pentacluster Scale'          : ([1, 1, 3, 1, 6],          ["Exotic"]),
            'Chinese Scale'                        : ([4, 2, 1, 4, 1],          ["Exotic"]),
            'Balinese Scale'                       : ([1, 2, 4, 1, 4],          ["Exotic"]),
            'Raga Vutari Scale'                    : ([4, 2, 1, 2, 1, 2],       ["Exotic"]),
            'Raga Madhuri Scale'                   : ([4, 1, 2, 2, 1, 1, 1],    ["Exotic"]),
            'Raga Viyogavarali Scale'              : ([1, 2, 2, 3, 3, 1],       ["Exotic"]),
            'Shostakovich Scale'                   : ([1, 2, 1, 2, 1, 2, 2, 1], ["Modern"]),
            'Blues Octatonic Scale'                : ([2, 1, 2, 1, 1, 2, 1, 2], ["Exotic"]),
            'Pyramid Hexatonic Scale'              : ([2, 1, 2, 1, 3, 3],       ["Exotic"]),
            'Romanian Scale'                       : ([4, 1, 3, 3, 1],          ["Exotic"]),
            'Gnossiennes Scale'                    : ([2, 1, 2, 2, 1, 3, 1],    ["Exotic"]),
            'Prometheus Scale'                     : ([2, 2, 2, 3, 1, 2],       ["Modern"]),
            'Adonai Malakh Scale'                  : ([1, 1, 1, 2, 2, 2, 1, 2], ["Exotic"]),
            'Houzam Scale'                         : ([3, 1, 1, 2, 2, 2, 1],    ["Exotic"]),
            'Rock and Roll Scale'                  : ([3, 1, 1, 2, 2, 1, 2],    ["Exotic"]),
            'Phrgian Natural 6 Scale'              : ([1, 2, 2, 2, 2, 1, 2],    ["Jazz"]),
            'Lydian Augmented Scale'               : ([2, 2, 2, 2, 1, 2, 1],    ["Jazz"]),
            'Lydian Dominant Scale'                : ([2, 2, 2, 1, 2, 1, 2],    ["Jazz"]),
            'Ionian Scale'                         : ([2, 2, 1, 2, 2, 2, 1],    ["Modal", "Modern"]),
            'Dorian Scale'                         : ([2, 1, 2, 2, 2, 1, 2],    ["Modal", "Modern"]),
            'Phrygian Scale'                       : ([1, 2, 2, 2, 1, 2, 2],    ["Modal", "Modern"]),
            'Lydian Scale'                         : ([2, 2, 2, 1, 2, 2, 1],    ["Modal", "Modern"]),
            'Mixolydian Scale'                     : ([2, 2, 1, 2, 2, 1, 2],    ["Jazz","Modal", "Modern"]),
            'Aeolian Scale'                        : ([2, 1, 2, 2, 1, 2, 2],    ["Modal", "Modern"]),
            'Locrian Scale'                        : ([1, 2, 2, 1, 2, 2, 2],    ["Jazz", "Modern"]),
            'Super Locrian Scale'                  : ([1, 2, 1, 2, 2, 2, 2],    ["Jazz"]),
            'Melodic Minor Scale'                  : ([2, 1, 2, 2, 2, 2, 1],    ["Tonal"]),
            'Bebop Dominant Scale'                 : ([2, 2, 1, 2, 2, 1, 1, 1], ["Jazz"]),
            'Bebop Major Scale'                    : ([2, 2, 1, 2, 1, 1, 2, 1], ["Jazz"]),
            'Bebop Melodic Minor Scale'            : ([2, 1, 1, 1, 2, 2, 1, 2], ["Jazz"]),
            'Bebop Dorian Scale'                   : ([2, 1, 1, 1, 2, 2, 1, 2], ["Jazz"]),
            'Whole Tone Scale'                     : ([2, 2, 2, 2, 2, 2],       ["Exotic", "Modern"]),
            'Interval 2 Cycle'                     : ([2, 2, 2, 2, 2, 2],       ["Cycles"]),
            'Interval 10 Cycle'                    : ([10, 10, 10, 10, 10, 10], ["Cycles"]),
            'Interval 9 Cycle'                     : ([9, 9, 9, 9],             ["Cycles"]),
            'Interval 3 Cycle'                     : ([3, 3, 3, 3],             ["Cycles"]),
            'Interval 4 Cycle'                     : ([4, 4, 4],                ["Cycles"]),
            'Interval 8 Cycle'                     : ([8, 8, 8],                ["Cycles"]),
            'Interval 7 Cycle'                     : ([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],     ["Cycles"]),
            'Interval 5 Cycle'                     : ([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],     ["Cycles"]),
            'Interval 6 Cycle'                     : ([6, 6],                                   ["Cycles"]),
            'Compound Cycle 1:2'                   : ([1, 2, 1, 2, 1, 2, 1, 2],                                                     ["Cycles"]),
            'Compound Cycle 2:1'                   : ([2, 1, 2, 1, 2, 1, 2, 1],                                                     ["Cycles"]),
            'Compound Cycle 1:3'                   : ([1, 3, 1, 3, 1, 3],                                                           ["Cycles"]),
            'Compound Cycle 3:1'                   : ([3, 1, 3, 1, 3, 1, 3, 1],                                                     ["Cycles"]),
            'Compound Cycle 1:4'                   : ([1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4],     ["Cycles"]),
            'Compound Cycle 4:1'                   : ([4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],     ["Cycles"]),
            'Compound Cycle 2:3'                   : ([2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],     ["Cycles"]),
            'Compound Cycle 3:2'                   : ([3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2],     ["Cycles"]),
            'Compound Cycle 1:5'                   : ([1, 5, 1, 5],                                                                 ["Cycles"]),
            'Compound Cycle 5:1'                   : ([5, 1, 5, 1],                                                                 ["Cycles"]),
            'Compound Cycle 2:4'                   : ([2, 4, 2, 4],                                                                 ["Cycles"]),
            'Compound Cycle 4:2'                   : ([4, 2, 4, 2],                                                                 ["Cycles"]),
            'Compound Cycle 1:6'                   : ([1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6],     ["Cycles"]),
            'Compound Cycle 6:1'                   : ([6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1],     ["Cycles"]),
            'Compound Cycle 2:5'                   : ([2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5],     ["Cycles"]),
            'Compound Cycle 5:2'                   : ([5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2],     ["Cycles"]),
            'Compound Cycle 3:4'                   : ([3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],     ["Cycles"]),
            'Compound Cycle 4:3'                   : ([4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3],     ["Cycles"]),
            'Compound Cycle 1:7'                   : ([1, 7, 1, 7, 1, 7],                                                           ["Cycles"]),
            'Compound Cycle 7:1'                   : ([7, 1, 7, 1, 7, 1],                                                           ["Cycles"]),
            'Compound Cycle 2:6'                   : ([2, 6, 2, 6, 2, 6],                                                           ["Cycles"]),
            'Compound Cycle 6:2'                   : ([6, 2, 6, 2, 6, 2],                                                           ["Cycles"]),
            'Compound Cycle 3:5'                   : ([3, 5, 3, 5, 3, 5],                                                           ["Cycles"]),
            'Compound Cycle 5:3'                   : ([5, 3, 5, 3, 5, 3],                                                           ["Cycles"]),
            'Compound Cycle 1:8'                   : ([1, 8, 1, 8, 1, 8, 1, 8],                                                     ["Cycles"]),
            'Compound Cycle 8:1'                   : ([8, 1, 8, 1, 8, 1, 8, 1],                                                     ["Cycles"]),
            'Compound Cycle 2:7'                   : ([2, 7, 2, 7, 2, 7, 2, 7],                                                     ["Cycles"]),
            'Compound Cycle 7:2'                   : ([7, 2, 7, 2, 7, 2, 7, 2],                                                     ["Cycles"]),
            'Compound Cycle 2:7'                   : ([2, 7, 2, 7, 2, 7, 2, 7],                                                     ["Cycles"]),
            'Compound Cycle 3:6'                   : ([3, 6, 3, 6, 3, 6, 3, 6],                                                     ["Cycles"]),
            'Compound Cycle 6:3'                   : ([6, 3, 6, 3, 6, 3, 6, 3],                                                     ["Cycles"]),
            'Compound Cycle 4:5'                   : ([4, 5, 4, 5, 4, 5, 4, 5],                                                     ["Cycles"]),
            'Compound Cycle 5:4'                   : ([5, 4, 5, 4, 5, 4, 5, 4],                                                     ["Cycles"]),
            'Compound Cycle 1:9'                   : ([1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9],                                         ["Cycles"]),
            'Compound Cycle 9:1'                   : ([9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1],                                         ["Cycles"]),
            'Compound Cycle 2:8'                   : ([2, 8, 2, 8, 2, 8, 2, 8, 2, 8, 2, 8],                                         ["Cycles"]),
            'Compound Cycle 8:2'                   : ([8, 2, 8, 2, 8, 2, 8, 2, 8, 2, 8, 2],                                         ["Cycles"]),
            'Compound Cycle 3:7'                   : ([3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7],                                         ["Cycles"]),
            'Compound Cycle 7:3'                   : ([7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3],                                         ["Cycles"]),
            'Compound Cycle 4:6'                   : ([4, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6],                                         ["Cycles"]),
            'Compound Cycle 6:4'                   : ([6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4],                                         ["Cycles"]),
            'Compound Cycle 1:10'                  : ([1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10],     ["Cycles"]),
            'Compound Cycle 10:1'                  : ([10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1],     ["Cycles"]),
            'Compound Cycle 2:9'                   : ([2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9],     ["Cycles"]),
            'Compound Cycle 9:2'                   : ([9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2, 9, 2],     ["Cycles"]),
            'Compound Cycle 3:8'                   : ([3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8],     ["Cycles"]),
            'Compound Cycle 8:3'                   : ([8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3],     ["Cycles"]),
            'Compound Cycle 4:7'                   : ([4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7],     ["Cycles"]),
            'Compound Cycle 7:4'                   : ([7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4, 7, 4],     ["Cycles"]),
            'Compound Cycle 5:6'                   : ([5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],     ["Cycles"]),
            'Compound Cycle 6:5'                   : ([6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5],     ["Cycles"]),
            'Compound Cycle 1:11'                  : ([1, 11],                                                                      ["Cycles"]),
            'Compound Cycle 11:1'                  : ([11, 1],                                                                      ["Cycles"]),
            'Compound Cycle 2:10'                  : ([2, 10],                                                                      ["Cycles"]),
            'Compound Cycle 10:2'                  : ([10, 2],                                                                      ["Cycles"]),
            'Compound Cycle 3:9'                   : ([3, 9],                                                                       ["Cycles"]),
            'Compound Cycle 9:3'                   : ([9, 3],                                                                       ["Cycles"]),
            'Compound Cycle 4:8'                   : ([4, 8],                                                                       ["Cycles"]),
            'Compound Cycle 8:4'                   : ([8, 4],                                                                       ["Cycles"]),
            'Compound Cycle 5:7'                   : ([5, 7],                                                                       ["Cycles"]),
            'Compound Cycle 7:5'                   : ([7, 5],                                                                       ["Cycles"])
            }
