scales = {  'Major Scale'                          : ([2, 2, 1, 2, 2, 2, 1], "Classical, Jazz, Rock, Pop Music"),
            'Natural Minor Scale'                  : ([2, 1, 2, 2, 1, 2, 2], "Classical Music"),
            'Minor Pentatonic Scale'               : ([3, 2, 2, 3, 2], "Classical Music"),
            'Blues Scale'                          : ([3, 2, 1, 1, 3, 2], "Blues"),
            'Harmonic Minor Scale'                 : ([2, 1, 2, 2, 1, 3, 1], "Jazz Music"),
            'Chromatic Scale'                      : ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "Classical Music"),
            'Half-Step-Minor-Third Scale'          : ([1, 3, 1, 3, 1, 3], "Classical Music"),
            'Pentatonic Scale'                     : ([2, 2, 3, 2, 3], "Blues"),
            'Octatonic Scale'                      : ([1, 2, 1, 2, 1, 2, 1, 2], "Classical Music"),
            'Algerian Scale'                       : ([2, 1, 2, 1, 1, 1, 3, 1], "Exotic Music"),
            'Harmonic Major Scale'                 : ([2, 2, 1, 2, 1, 3, 1], "Exotic Music"),
            'Double Harmonic Major (Arabic) Scale' : ([1, 3, 1, 2, 1, 3, 1], "Exotic Music"),
            'Double Harmonic Minor Scale'          : ([0, 1, 3, 1, 1, 3, 1], "Exotic Music"),
            'Hungarian Gypsy Scale Scale'          : ([2, 1, 3, 1, 1, 3, 1], "Exotic Music"),
            'Hungarian Minor Scale'                : ([2, 1, 3, 1, 1, 3, 1], "Exotic Music"),
            'Hungarian Folk Scale'                 : ([1, 3, 1, 2, 1, 3, 1], "Exotic Music"),
            'Phrygian Dominant (Jewish) Scale'     : ([1, 3, 1, 2, 1, 2, 2], "Exotic Music"),
            'Egyptian Scale Scale'                 : ([2, 1, 3, 1, 1, 3, 1], "Exotic Music"),
            'Eskimo Tetratonic Scale'              : ([2, 2, 3, 5], "Exotic Music"),
            'Eskimo Hexatonic Scale'               : ([2, 2, 2, 2, 1, 3], "Exotic Music"),
            'Scottish Hexatonic Scale'             : ([2, 2, 1, 2, 2, 3], "Exotic Music"),
            'Oriental Scale'                       : ([2, 3, 4, 1, 2], "Exotic Music"),
            'Oriental Pentacluster Scale'          : ([1, 1, 3, 1, 6], "Exotic Music"),
            'Chinese Scale'                        : ([4, 2, 1, 4, 1], "Exotic Music"),
            'Balinese Scale'                       : ([1, 2, 4, 1, 4], "Exotic Music"),
            'Raga Vutari Scale'                    : ([4, 2, 1, 2, 1, 2], "Exotic Music"),
            'Raga Madhuri Scale'                   : ([4, 1, 2, 2, 1, 1, 1], "Exotic Music"),
            'Raga Viyogavarali Scale'              : ([1, 2, 2, 3, 3, 1], "Exotic Music"),
            'Shostakovich Scale'                   : ([1, 2, 1, 2, 1, 2, 2, 1], "Exotic Music"),
            'Blues Octatonic Scale'                : ([2, 1, 2, 1, 1, 2, 1, 2], "Exotic Music"),
            'Pyramid Hexatonic Scale'              : ([2, 1, 2, 1, 3, 3], "Exotic Music"),
            'Romanian Scale'                       : ([4, 1, 3, 3, 1], "Exotic Music"),
            'Gnossiennes Scale'                    : ([2, 1, 2, 2, 1, 3, 1], "Exotic Music"),
            'Prometheus Scale'                     : ([2, 2, 2, 3, 1, 2], "Exotic Music"),
            'Adonai Malakh Scale'                  : ([1, 1, 1, 2, 2, 2, 1, 2], "Exotic Music"),
            'Houzam Scale'                         : ([3, 1, 1, 2, 2, 2, 1], "Exotic Music"),
            'Rock and Roll Scale'                  : ([3, 1, 1, 2, 2, 1, 2], "Exotic Music"),
            'Phrgian Natural 6 Scale'              : ([1, 2, 2, 2, 2, 1, 2], "Jazz Music"),
            'Lydian Augmented Scale'               : ([2, 2, 2, 2, 1, 2, 1], "Jazz Music"),
            'Lydian Dominant Scale'                : ([2, 2, 2, 1, 2, 1, 2], "Jazz Music"),
            'Mixolydian Scale'                     : ([2, 2, 1, 2, 2, 1, 2], "Jazz Music"),
            'Locrian Scale'                        : ([1, 2, 2, 1, 2, 2, 2], "Jazz Music"),
            'Super Locrian Scale'                  : ([1, 2, 1, 2, 2, 2, 2], "Jazz Music"),
            'Melodic Minor Scale'                  : ([2, 1, 2, 2, 2, 2, 1], "Jazz Music"),
            'Bebop Dominant Scale'                 : ([2, 2, 1, 2, 2, 1, 1, 1], "Jazz Music"),
            'Bebop Major Scale'                    : ([2, 2, 1, 2, 1, 1, 2, 1], "Jazz Music"),
            'Bebop Melodic Minor Scale'            : ([2, 1, 1, 1, 2, 2, 1, 2], "Jazz Music"),
            'Bebop Dorian Scale'                   : ([2, 1, 1, 1, 2, 2, 1, 2], "Jazz Music"),
            }
